# https://www.home-assistant.io/integrations/homeassistant/

homeassistant:
  debug: true

recorder:

logbook:

history:

system_health:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.polestar_api: debug
    pypolestar: debug
